### ISSUE TITLE
Typo? unknown field uid

### ISSUE THREAD

**Issue by juresaht2** [Neo23x0/auditd#125]
I get the error:
```
augenrules: -F unknown field: uid
```

I assume this is a typo:
https://github.com/Neo23x0/auditd/blob/master/audit.rules#L464
```
## Privilege Abuse
### The purpose of this rule is to detect when an admin may be abusing power by looking in user's home dir.
-a always,exit -F dir=/home -F uid=0 -F auid>=1000 -F auid!=-1 -C auid!=obj_uid -k power_abuse
```
...should be...
```
## Privilege Abuse
### The purpose of this rule is to detect when an admin may be abusing power by looking in user's home dir.
-a always,exit -F dir=/home -F auid=0 -F auid>=1000 -F auid!=-1 -C auid!=obj_uid -k power_abuse
```

**Comment by Neo23x0** [comment]
Thanks

**Comment by as9k1** [comment]
Hey, I think the new version of this rule is unfortunately broken now, because AUID is now required to be both 0 and >=1000 at the same time, which is never going to happen.

The original version of the rule is working fine in my testing on Ubuntu 22.04. I don't see the "_F unknown field: uid"-issue that @juresaht2 reported (might be a different issue on his end).
